<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>future on ThingsDB documentation</title><link>https://docs.thingsdb.net/v1/data-types/future/</link><description>Recent content in future on ThingsDB documentation</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><atom:link href="https://docs.thingsdb.net/v1/data-types/future/index.xml" rel="self" type="application/rss+xml"/><item><title>then</title><link>https://docs.thingsdb.net/v1/data-types/future/then/</link><pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate><guid>https://docs.thingsdb.net/v1/data-types/future/then/</guid><description>Function then accepts a closure as argument which will be executed only when the future is successful. The code inside the closure will only generate a change then the closure code is executed. The return value of the closure will be used as the new future value.
The closure will be called with the same arguments as given to the future, except for the first argument, which can be the result of a module.</description></item><item><title>else</title><link>https://docs.thingsdb.net/v1/data-types/future/else/</link><pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate><guid>https://docs.thingsdb.net/v1/data-types/future/else/</guid><description>Function else accepts a closure as argument which will be executed only when the future is using a module which has failed with some error. The code inside the closure will only generate a change when the closure code is executed. The return value of the closure will be used as the new future value.
The closure will be called with the same arguments as given to the future, except for the first argument, which is the error from the module.</description></item></channel></rss>